// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB44LWvuEsMHJVrEY7WfaNtyf1yqyMYf8Y',
    appId: '1:925106320602:web:9e3e3e05788385ef1121e3',
    messagingSenderId: '925106320602',
    projectId: 'law1912-flutter-course-fcc',
    authDomain: 'law1912-flutter-course-fcc.firebaseapp.com',
    storageBucket: 'law1912-flutter-course-fcc.appspot.com',
    measurementId: 'G-9F0PCNRHQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt20-0wQw8xel43DeEX9GQSiBiz0SrCSQ',
    appId: '1:925106320602:android:f68fd04e506814f41121e3',
    messagingSenderId: '925106320602',
    projectId: 'law1912-flutter-course-fcc',
    storageBucket: 'law1912-flutter-course-fcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpP-WD76Y1L8fxxLPwz4BwdfZO0s8Am4E',
    appId: '1:925106320602:ios:18a8921428c11c5f1121e3',
    messagingSenderId: '925106320602',
    projectId: 'law1912-flutter-course-fcc',
    storageBucket: 'law1912-flutter-course-fcc.appspot.com',
    iosBundleId: 'com.example.freeCodeCamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpP-WD76Y1L8fxxLPwz4BwdfZO0s8Am4E',
    appId: '1:925106320602:ios:18a8921428c11c5f1121e3',
    messagingSenderId: '925106320602',
    projectId: 'law1912-flutter-course-fcc',
    storageBucket: 'law1912-flutter-course-fcc.appspot.com',
    iosBundleId: 'com.example.freeCodeCamp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB44LWvuEsMHJVrEY7WfaNtyf1yqyMYf8Y',
    appId: '1:925106320602:web:3923d227cb28f7eb1121e3',
    messagingSenderId: '925106320602',
    projectId: 'law1912-flutter-course-fcc',
    authDomain: 'law1912-flutter-course-fcc.firebaseapp.com',
    storageBucket: 'law1912-flutter-course-fcc.appspot.com',
    measurementId: 'G-14E6G6B0R1',
  );
}
